// Generated by generate-locations.mjs from idfkit's doc_locations.json. Do not edit.
// 816 object types across 79 section paths.

/**
 * Documentation section paths, each paired with the tab-separated object types
 * documented there.
 *
 * Anchors are omitted because they are a pure function of the object type; the
 * generator verifies that for every entry before writing this file. Storing the
 * mapping this way costs a third of the JSON it came from, which matters
 * because `@idfkit/core` is loaded in browsers.
 *
 * @internal
 */
export const DOC_LOCATIONS: readonly (readonly [path: string, types: string])[] = [
  [
    'io-reference/overview/group-variable-refrigerant-flow-equipment/#',
    'AirConditioner:VariableRefrigerantFlow\tAirConditioner:VariableRefrigerantFlow:FluidTemperatureControl\tAirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR\tZoneTerminalUnitList',
  ],
  [
    'io-reference/overview/group-air-distribution/#',
    'AirLoopHVAC\tAirLoopHVAC:ControllerList\tAirLoopHVAC:OutdoorAirSystem\tAirLoopHVAC:OutdoorAirSystem:EquipmentList\tAvailabilityManagerAssignmentList\tOutdoorAir:Mixer\tOutdoorAir:Node\tOutdoorAir:NodeList',
  ],
  [
    'io-reference/overview/group-air-path/#',
    'AirLoopHVAC:DedicatedOutdoorAirSystem\tAirLoopHVAC:ExhaustSystem\tAirLoopHVAC:Mixer\tAirLoopHVAC:ReturnPath\tAirLoopHVAC:ReturnPlenum\tAirLoopHVAC:Splitter\tAirLoopHVAC:SupplyPath\tAirLoopHVAC:SupplyPlenum\tAirLoopHVAC:ZoneMixer\tAirLoopHVAC:ZoneSplitter\tZoneHVAC:ExhaustControl',
  ],
  [
    'io-reference/overview/group-unitary-equipment/#',
    'AirLoopHVAC:Unitary:Furnace:HeatCool\tAirLoopHVAC:Unitary:Furnace:HeatOnly\tAirLoopHVAC:UnitaryHeatCool\tAirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass\tAirLoopHVAC:UnitaryHeatOnly\tAirLoopHVAC:UnitaryHeatPump:AirToAir\tAirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed\tAirLoopHVAC:UnitaryHeatPump:WaterToAir\tAirLoopHVAC:UnitarySystem\tUnitarySystemPerformance:Multispeed',
  ],
  [
    'io-reference/overview/group-air-distribution-equipment/#',
    'AirTerminal:DualDuct:ConstantVolume\tAirTerminal:DualDuct:VAV\tAirTerminal:DualDuct:VAV:OutdoorAir\tAirTerminal:SingleDuct:ConstantVolume:CooledBeam\tAirTerminal:SingleDuct:ConstantVolume:FourPipeBeam\tAirTerminal:SingleDuct:ConstantVolume:FourPipeInduction\tAirTerminal:SingleDuct:ConstantVolume:NoReheat\tAirTerminal:SingleDuct:ConstantVolume:Reheat\tAirTerminal:SingleDuct:Mixer\tAirTerminal:SingleDuct:ParallelPIU:Reheat\tAirTerminal:SingleDuct:VAV:Reheat\tAirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan',
  ],
  [
    'io-reference/overview/group-user-defined-hvac-and-plant-component/#',
    'AirTerminal:SingleDuct:UserDefined\tCoil:UserDefined\tPlantComponent:UserDefined\tPlantEquipmentOperation:UserDefined\tZoneHVAC:ForcedAir:UserDefined',
  ],
  [
    'io-reference/overview/group-airflow-network/#',
    'AirflowNetwork:Distribution:Component:Coil\tAirflowNetwork:Distribution:Component:ConstantPressureDrop\tAirflowNetwork:Distribution:Component:Duct\tAirflowNetwork:Distribution:Component:Fan\tAirflowNetwork:Distribution:Component:HeatExchanger\tAirflowNetwork:Distribution:Component:Leak\tAirflowNetwork:Distribution:Component:LeakageRatio\tAirflowNetwork:Distribution:Component:OutdoorAirFlow\tAirflowNetwork:Distribution:Component:ReliefAirFlow\tAirflowNetwork:Distribution:Component:TerminalUnit\tAirflowNetwork:Distribution:DuctSizing\tAirflowNetwork:Distribution:DuctViewFactors\tAirflowNetwork:Distribution:Linkage\tAirflowNetwork:Distribution:Node\tAirflowNetwork:IntraZone:Linkage\tAirflowNetwork:IntraZone:Node\tAirflowNetwork:MultiZone:Component:DetailedOpening\tAirflowNetwork:MultiZone:Component:HorizontalOpening\tAirflowNetwork:MultiZone:Component:SimpleOpening\tAirflowNetwork:MultiZone:Component:ZoneExhaustFan\tAirflowNetwork:MultiZone:ExternalNode\tAirflowNetwork:MultiZone:ReferenceCrackConditions\tAirflowNetwork:MultiZone:SpecifiedFlowRate\tAirflowNetwork:MultiZone:Surface\tAirflowNetwork:MultiZone:Surface:Crack\tAirflowNetwork:MultiZone:Surface:EffectiveLeakageArea\tAirflowNetwork:MultiZone:WindPressureCoefficientArray\tAirflowNetwork:MultiZone:WindPressureCoefficientValues\tAirflowNetwork:MultiZone:Zone\tAirflowNetwork:OccupantVentilationControl\tAirflowNetwork:SimulationControl\tAirflowNetwork:ZoneControl:PressureController\tDuct:Loss:Conduction\tDuct:Loss:Leakage\tDuct:Loss:MakeupAir',
  ],
  [
    'io-reference/overview/group-system-availability-managers/#',
    'AvailabilityManager:DifferentialThermostat\tAvailabilityManager:HighTemperatureTurnOff\tAvailabilityManager:HighTemperatureTurnOn\tAvailabilityManager:HybridVentilation\tAvailabilityManager:LowTemperatureTurnOff\tAvailabilityManager:LowTemperatureTurnOn\tAvailabilityManager:NightCycle\tAvailabilityManager:NightVentilation\tAvailabilityManager:OptimumStart\tAvailabilityManager:Scheduled\tAvailabilityManager:ScheduledOff\tAvailabilityManager:ScheduledOn',
  ],
  [
    'io-reference/overview/group-plant-equipment/#',
    'Boiler:HotWater\tBoiler:Steam\tCentralHeatPumpSystem\tChiller:Absorption\tChiller:Absorption:Indirect\tChiller:CombustionTurbine\tChiller:ConstantCOP\tChiller:Electric:ASHRAE205\tChiller:Electric:EIR\tChiller:Electric:ReformulatedEIR\tChiller:EngineDriven\tChillerHeater:Absorption:DirectFired\tChillerHeater:Absorption:DoubleEffect\tChillerHeaterPerformance:Electric:EIR\tDistrictCooling\tDistrictHeating:Steam\tDistrictHeating:Water\tHeatPump:AirToWater\tHeatPump:PlantLoop:EIR:Cooling\tHeatPump:PlantLoop:EIR:Heating\tHeatPump:WaterToWater:EquationFit:Cooling\tHeatPump:WaterToWater:EquationFit:Heating\tHeatPump:WaterToWater:ParameterEstimation:Cooling\tHeatPump:WaterToWater:ParameterEstimation:Heating\tPlantComponent:TemperatureSource',
  ],
  [
    'io-reference/overview/group-node-branch-management/#',
    'Branch\tBranchList\tConnector:Mixer\tConnector:Splitter\tConnectorList\tDuct\tNodeList\tPipe:Adiabatic\tPipe:Adiabatic:Steam\tPipe:Indoor\tPipe:Outdoor\tPipe:Underground\tPipingSystem:Underground:Domain\tPipingSystem:Underground:PipeCircuit\tPipingSystem:Underground:PipeSegment',
  ],
  [
    'io-reference/overview/group-simulation-parameters/#',
    'Building\tConvergenceLimits\tHVACSystemRootFindingAlgorithm\tHeatBalanceAlgorithm\tHeatBalanceSettings:ConductionFiniteDifference\tMeter:Custom\tMeter:CustomDecrement\tOutput:DebuggingData\tOutput:Diagnostics\tOutput:PreprocessorMessage\tPerformancePrecisionTradeoffs\tShadowCalculation\tSimulationControl\tSurfaceConvectionAlgorithm:Inside\tSurfaceConvectionAlgorithm:Outside\tTimestep\tVersion\tZoneAirContaminantBalance\tZoneAirHeatBalanceAlgorithm\tZoneCapacitanceMultiplier:ResearchSpecial',
  ],
  [
    'io-reference/overview/group-thermal-zone-description-geometry/#',
    'BuildingSurface:Detailed\tCeiling:Adiabatic\tCeiling:Interzone\tDoor\tDoor:Interzone\tFenestrationSurface:Detailed\tFloor:Adiabatic\tFloor:Detailed\tFloor:GroundContact\tFloor:Interzone\tGlazedDoor\tGlazedDoor:Interzone\tGlobalGeometryRules\tInternalMass\tRoof\tRoofCeiling:Detailed\tShading:Fin\tShading:Fin:Projection\tShading:Overhang\tShading:Overhang:Projection\tShadingProperty:Reflectance\tSpace\tSpaceList\tWall:Adiabatic\tWall:Detailed\tWall:Exterior\tWall:Interzone\tWall:Underground\tWindow\tWindow:Interzone\tWindowProperty:AirflowControl\tWindowProperty:FrameAndDivider\tWindowProperty:StormWindow\tWindowShadingControl\tZone\tZoneGroup\tZoneList',
  ],
  [
    'io-reference/energyplus-economics/cost-estimating/#',
    'Chiller:Electric\tCoil:Heating:Fuel\tComponentCost:Adjustments\tComponentCost:LineItem\tComponentCost:Reference\tConstruction\tDaylighting:Controls\tGenerator:Photovoltaic\tLights\tShading:Zone:Detailed',
  ],
  [
    'io-reference/overview/group-coil-cooling-dx/#',
    'Coil:Cooling:DX\tCoil:Cooling:DX:CurveFit:OperatingMode\tCoil:Cooling:DX:CurveFit:Performance\tCoil:Cooling:DX:CurveFit:Speed',
  ],
  [
    'io-reference/overview/group-heating-and-cooling-coils/#',
    'Coil:Cooling:DX:MultiSpeed\tCoil:Cooling:DX:SingleSpeed\tCoil:Cooling:DX:SingleSpeed:ThermalStorage\tCoil:Cooling:DX:TwoSpeed\tCoil:Cooling:DX:TwoStageWithHumidityControlMode\tCoil:Cooling:DX:VariableRefrigerantFlow\tCoil:Cooling:DX:VariableRefrigerantFlow:FluidTemperatureControl\tCoil:Cooling:DX:VariableSpeed\tCoil:Cooling:Water\tCoil:Cooling:Water:DetailedGeometry\tCoil:Cooling:WaterToAirHeatPump:EquationFit\tCoil:Cooling:WaterToAirHeatPump:ParameterEstimation\tCoil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit\tCoil:Heating:DX:MultiSpeed\tCoil:Heating:DX:SingleSpeed\tCoil:Heating:DX:VariableRefrigerantFlow\tCoil:Heating:DX:VariableRefrigerantFlow:FluidTemperatureControl\tCoil:Heating:DX:VariableSpeed\tCoil:Heating:Desuperheater\tCoil:Heating:Electric\tCoil:Heating:Electric:MultiStage\tCoil:Heating:Gas:MultiStage\tCoil:Heating:Steam\tCoil:Heating:Water\tCoil:Heating:WaterToAirHeatPump:EquationFit\tCoil:Heating:WaterToAirHeatPump:ParameterEstimation\tCoil:Heating:WaterToAirHeatPump:VariableSpeedEquationFit\tCoil:WaterHeating:AirToWaterHeatPump:Pumped\tCoil:WaterHeating:AirToWaterHeatPump:VariableSpeed\tCoil:WaterHeating:AirToWaterHeatPump:Wrapped\tCoil:WaterHeating:Desuperheater\tCoilPerformance:DX:Cooling\tCoilSystem:Cooling:DX\tCoilSystem:Cooling:DX:HeatExchangerAssisted\tCoilSystem:Cooling:Water\tCoilSystem:Cooling:Water:HeatExchangerAssisted\tCoilSystem:Heating:DX\tCoilSystem:IntegratedHeatPump:AirSource',
  ],
  [
    'io-reference/overview/group-internal-gains-people-lights-other/#',
    'ComfortViewFactorAngles\tElectricEquipment\tElectricEquipment:ITE:AirCooled\tGasEquipment\tHotWaterEquipment\tIndoorLivingWall\tOtherEquipment\tPeople\tSteamEquipment\tSurfaceContaminantSourceAndSink:Generic:BoundaryLayerDiffusion\tSurfaceContaminantSourceAndSink:Generic:DepositionVelocitySink\tSurfaceContaminantSourceAndSink:Generic:PressureDriven\tSwimmingPool:Indoor\tZoneBaseboard:OutdoorTemperatureControlled\tZoneContaminantSourceAndSink:CarbonDioxide\tZoneContaminantSourceAndSink:Generic:Constant\tZoneContaminantSourceAndSink:Generic:CutoffModel\tZoneContaminantSourceAndSink:Generic:DecaySource\tZoneContaminantSourceAndSink:Generic:DepositionRateSink',
  ],
  [
    'io-reference/overview/group-advanced-surface-concepts/#',
    'ComplexFenestrationProperty:SolarAbsorbedLayers\tFoundation:Kiva\tFoundation:Kiva:Settings\tGeometryTransform\tSurfaceControl:MovableInsulation\tSurfaceConvectionAlgorithm:Inside:AdaptiveModelSelections\tSurfaceConvectionAlgorithm:Inside:UserCurve\tSurfaceConvectionAlgorithm:Outside:AdaptiveModelSelections\tSurfaceConvectionAlgorithm:Outside:UserCurve\tSurfaceProperties:VaporCoefficients\tSurfaceProperty:ConvectionCoefficients\tSurfaceProperty:ConvectionCoefficients:MultipleSurface\tSurfaceProperty:ExposedFoundationPerimeter\tSurfaceProperty:ExteriorNaturalVentedCavity\tSurfaceProperty:GroundSurfaces\tSurfaceProperty:HeatBalanceSourceTerm\tSurfaceProperty:HeatTransferAlgorithm\tSurfaceProperty:HeatTransferAlgorithm:Construction\tSurfaceProperty:HeatTransferAlgorithm:MultipleSurface\tSurfaceProperty:HeatTransferAlgorithm:SurfaceList\tSurfaceProperty:IncidentSolarMultiplier\tSurfaceProperty:LocalEnvironment\tSurfaceProperty:OtherSideCoefficients\tSurfaceProperty:OtherSideConditionsModel\tSurfaceProperty:SolarIncidentInside\tSurfaceProperty:SurroundingSurfaces\tSurfaceProperty:Underwater\tZoneProperty:LocalEnvironment\tZoneProperty:UserViewFactors:BySurfaceName',
  ],
  ['io-reference/overview/group-compliance-objects/#', 'Compliance:Building'],
  [
    'io-reference/overview/group-plant-condenser-control/#',
    'CondenserEquipmentList\tCondenserEquipmentOperationSchemes\tPlantEquipmentList\tPlantEquipmentOperation:ChillerHeaterChangeover\tPlantEquipmentOperation:ComponentSetpoint\tPlantEquipmentOperation:CoolingLoad\tPlantEquipmentOperation:HeatingLoad\tPlantEquipmentOperation:OutdoorDewpoint\tPlantEquipmentOperation:OutdoorDewpointDifference\tPlantEquipmentOperation:OutdoorDryBulb\tPlantEquipmentOperation:OutdoorDryBulbDifference\tPlantEquipmentOperation:OutdoorRelativeHumidity\tPlantEquipmentOperation:OutdoorWetBulb\tPlantEquipmentOperation:OutdoorWetBulbDifference\tPlantEquipmentOperation:ThermalEnergyStorage\tPlantEquipmentOperation:Uncontrolled\tPlantEquipmentOperationSchemes',
  ],
  ['io-reference/overview/group-plant-condenser-loops/#', 'CondenserLoop\tPlantLoop'],
  [
    'io-reference/overview/group-surface-construction-elements/#',
    'Construction:AirBoundary\tConstruction:CfactorUndergroundWall\tConstruction:ComplexFenestrationState\tConstruction:FfactorGroundFloor\tConstruction:WindowDataFile\tConstruction:WindowEquivalentLayer\tConstructionProperty:InternalHeatSource\tMaterial\tMaterial:AirGap\tMaterial:InfraredTransparent\tMaterial:NoMass\tMaterial:RoofVegetation\tMaterialProperty:GlazingSpectralData\tMaterialProperty:HeatAndMoistureTransfer:Diffusion\tMaterialProperty:HeatAndMoistureTransfer:Redistribution\tMaterialProperty:HeatAndMoistureTransfer:Settings\tMaterialProperty:HeatAndMoistureTransfer:SorptionIsotherm\tMaterialProperty:HeatAndMoistureTransfer:Suction\tMaterialProperty:HeatAndMoistureTransfer:ThermalConductivity\tMaterialProperty:MoisturePenetrationDepth:Settings\tMaterialProperty:PhaseChange\tMaterialProperty:PhaseChangeHysteresis\tMaterialProperty:VariableAbsorptance\tMaterialProperty:VariableThermalConductivity\tMatrix:TwoDimension\tWindowGap:DeflectionState\tWindowGap:SupportPillar\tWindowMaterial:Blind\tWindowMaterial:Blind:EquivalentLayer\tWindowMaterial:ComplexShade\tWindowMaterial:Drape:EquivalentLayer\tWindowMaterial:Gap\tWindowMaterial:Gap:EquivalentLayer\tWindowMaterial:Gas\tWindowMaterial:GasMixture\tWindowMaterial:Glazing\tWindowMaterial:Glazing:EquivalentLayer\tWindowMaterial:Glazing:RefractionExtinctionMethod\tWindowMaterial:GlazingGroup:Thermochromic\tWindowMaterial:Screen\tWindowMaterial:Screen:EquivalentLayer\tWindowMaterial:Shade\tWindowMaterial:Shade:EquivalentLayer\tWindowMaterial:SimpleGlazingSystem\tWindowThermalModel:Params',
  ],
  [
    'io-reference/overview/group-controllers/#',
    'Controller:MechanicalVentilation\tController:OutdoorAir\tController:WaterCoil\tZoneHVAC:EnergyRecoveryVentilator:Controller',
  ],
  [
    'io-reference/overview/group-condenser-equipment/#',
    'CoolingTower:SingleSpeed\tCoolingTower:TwoSpeed\tCoolingTower:VariableSpeed\tCoolingTower:VariableSpeed:Merkel\tCoolingTowerPerformance:CoolTools\tCoolingTowerPerformance:YorkCalc\tEvaporativeFluidCooler:SingleSpeed\tEvaporativeFluidCooler:TwoSpeed\tFluidCooler:SingleSpeed\tFluidCooler:TwoSpeed\tGroundHeatExchanger:HorizontalTrench\tGroundHeatExchanger:Pond\tGroundHeatExchanger:ResponseFactors\tGroundHeatExchanger:Slinky\tGroundHeatExchanger:Surface\tGroundHeatExchanger:System\tGroundHeatExchanger:Vertical:Array\tGroundHeatExchanger:Vertical:Properties\tGroundHeatExchanger:Vertical:Single\tGroundHeatExchanger:Vertical:Sizing:Rectangle\tHeatExchanger:FluidToFluid',
  ],
  ['io-reference/energyplus-economics/currencytype/#', 'CurrencyType'],
  [
    'io-reference/overview/group-performance-curves/#',
    'Curve:Bicubic\tCurve:Biquadratic\tCurve:ChillerPartLoadWithLift\tCurve:Cubic\tCurve:CubicLinear\tCurve:DoubleExponentialDecay\tCurve:Exponent\tCurve:ExponentialDecay\tCurve:ExponentialSkewNormal\tCurve:FanPressureRise\tCurve:Functional:PressureDrop\tCurve:Linear\tCurve:QuadLinear\tCurve:Quadratic\tCurve:QuadraticLinear\tCurve:Quartic\tCurve:QuintLinear\tCurve:RectangularHyperbola1\tCurve:RectangularHyperbola2\tCurve:Sigmoid\tCurve:Triquadratic',
  ],
  [
    'io-reference/overview/group-daylighting/#',
    'Daylighting:DELight:ComplexFenestration\tDaylighting:ReferencePoint\tDaylightingDevice:LightWell\tDaylightingDevice:Shelf\tDaylightingDevice:Tubular\tOutput:IlluminanceMap\tOutputControl:IlluminanceMap:Style',
  ],
  [
    'io-reference/overview/group-humidifiers-and-dehumidifiers/#',
    'Dehumidifier:Desiccant:NoFans\tDehumidifier:Desiccant:System\tHumidifier:Steam:Electric\tHumidifier:Steam:Gas',
  ],
  [
    'io-reference/overview/group-demand-limiting-controls/#',
    'DemandManager:ElectricEquipment\tDemandManager:ExteriorLights\tDemandManager:Lights\tDemandManager:Thermostats\tDemandManager:Ventilation\tDemandManagerAssignmentList',
  ],
  [
    'io-reference/overview/group-design-objects/#',
    'DesignSpecification:AirTerminal:Sizing\tDesignSpecification:OutdoorAir\tDesignSpecification:OutdoorAir:SpaceList\tDesignSpecification:ZoneAirDistribution\tDesignSpecification:ZoneHVAC:Sizing\tOutputControl:Sizing:Style\tSizing:Parameters\tSizing:Plant\tSizing:System\tSizing:Zone',
  ],
  [
    'io-reference/overview/group-electric-load-center-generator/#',
    'ElectricLoadCenter:Distribution\tElectricLoadCenter:Generators\tElectricLoadCenter:Inverter:FunctionOfPower\tElectricLoadCenter:Inverter:LookUpTable\tElectricLoadCenter:Inverter:PVWatts\tElectricLoadCenter:Inverter:Simple\tElectricLoadCenter:Storage:Battery\tElectricLoadCenter:Storage:Converter\tElectricLoadCenter:Storage:LiIonNMCBattery\tElectricLoadCenter:Storage:Simple\tElectricLoadCenter:Transformer\tGenerator:CombustionTurbine\tGenerator:FuelCell\tGenerator:FuelCell:AirSupply\tGenerator:FuelCell:AuxiliaryHeater\tGenerator:FuelCell:ElectricalStorage\tGenerator:FuelCell:ExhaustGasToWaterHeatExchanger\tGenerator:FuelCell:Inverter\tGenerator:FuelCell:PowerModule\tGenerator:FuelCell:StackCooler\tGenerator:FuelCell:WaterSupply\tGenerator:FuelSupply\tGenerator:InternalCombustionEngine\tGenerator:MicroCHP\tGenerator:MicroCHP:NonNormalizedParameters\tGenerator:MicroTurbine\tGenerator:PVWatts\tGenerator:WindTurbine\tPhotovoltaicPerformance:EquivalentOne-Diode\tPhotovoltaicPerformance:Sandia\tPhotovoltaicPerformance:Simple',
  ],
  [
    'io-reference/overview/group-energy-management-system-ems/#',
    'EnergyManagementSystem:Actuator\tEnergyManagementSystem:ConstructionIndexVariable\tEnergyManagementSystem:CurveOrTableIndexVariable\tEnergyManagementSystem:GlobalVariable\tEnergyManagementSystem:InternalVariable\tEnergyManagementSystem:MeteredOutputVariable\tEnergyManagementSystem:OutputVariable\tEnergyManagementSystem:Program\tEnergyManagementSystem:ProgramCallingManager\tEnergyManagementSystem:Sensor\tEnergyManagementSystem:Subroutine\tEnergyManagementSystem:TrendVariable',
  ],
  [
    'io-reference/input-for-output/#',
    'EnvironmentalImpactFactors\tFuelFactors\tOutput:Constructions\tOutput:DaylightFactors\tOutput:EnergyManagementSystem\tOutput:EnvironmentalImpactFactors\tOutput:JSON\tOutput:SQLite\tOutput:Schedules\tOutput:Surfaces:Drawing\tOutput:Surfaces:List\tOutput:Variable\tOutput:VariableDictionary\tOutputControl:Files\tOutputControl:ReportingTolerances\tOutputControl:ResilienceSummaries\tOutputControl:SurfaceColorScheme\tOutputControl:Timestamp',
  ],
  [
    'io-reference/overview/group-evaporative-coolers/#',
    'EvaporativeCooler:Direct:CelDekPad\tEvaporativeCooler:Direct:ResearchSpecial\tEvaporativeCooler:Indirect:CelDekPad\tEvaporativeCooler:Indirect:ResearchSpecial\tEvaporativeCooler:Indirect:WetCoil',
  ],
  [
    'io-reference/overview/group-exterior-energy-use-equipment/#',
    'Exterior:FuelEquipment\tExterior:Lights\tExterior:WaterEquipment',
  ],
  [
    'io-reference/overview/group-externalinterface/#',
    'ExternalInterface\tExternalInterface:Actuator\tExternalInterface:FunctionalMockupUnitExport:From:Variable\tExternalInterface:FunctionalMockupUnitExport:To:Actuator\tExternalInterface:FunctionalMockupUnitExport:To:Schedule\tExternalInterface:FunctionalMockupUnitExport:To:Variable\tExternalInterface:FunctionalMockupUnitImport\tExternalInterface:FunctionalMockupUnitImport:From:Variable\tExternalInterface:FunctionalMockupUnitImport:To:Actuator\tExternalInterface:FunctionalMockupUnitImport:To:Schedule\tExternalInterface:FunctionalMockupUnitImport:To:Variable\tExternalInterface:Schedule\tExternalInterface:Variable',
  ],
  [
    'io-reference/overview/group-fans/#',
    'Fan:ComponentModel\tFan:ConstantVolume\tFan:OnOff\tFan:SystemModel\tFan:VariableVolume\tFan:ZoneExhaust\tFanPerformance:NightVentilation',
  ],
  [
    'io-reference/overview/group-operational-faults/#',
    'FaultModel:EnthalpySensorOffset:OutdoorAir\tFaultModel:EnthalpySensorOffset:ReturnAir\tFaultModel:Fouling:AirFilter\tFaultModel:Fouling:Boiler\tFaultModel:Fouling:Chiller\tFaultModel:Fouling:Coil\tFaultModel:Fouling:CoolingTower\tFaultModel:Fouling:EvaporativeCooler\tFaultModel:HumidistatOffset\tFaultModel:HumiditySensorOffset:OutdoorAir\tFaultModel:TemperatureSensorOffset:ChillerSupplyWater\tFaultModel:TemperatureSensorOffset:CoilSupplyAir\tFaultModel:TemperatureSensorOffset:CondenserSupplyWater\tFaultModel:TemperatureSensorOffset:OutdoorAir\tFaultModel:TemperatureSensorOffset:ReturnAir\tFaultModel:ThermostatOffset',
  ],
  [
    'io-reference/overview/group-fluid-properties/#',
    'FluidProperties:Concentration\tFluidProperties:GlycolConcentration\tFluidProperties:Name\tFluidProperties:Saturated\tFluidProperties:Superheated\tFluidProperties:Temperatures',
  ],
  ['io-reference/overview/group-detailed-ground-heat-transfer/#', 'GroundHeatTransfer:Control'],
  [
    'io-reference/hvac-template-objects/group-hvac-templates/#',
    'HVACTemplate:Plant:Boiler\tHVACTemplate:Plant:Boiler:ObjectReference\tHVACTemplate:Plant:ChilledWaterLoop\tHVACTemplate:Plant:Chiller\tHVACTemplate:Plant:Chiller:ObjectReference\tHVACTemplate:Plant:HotWaterLoop\tHVACTemplate:Plant:MixedWaterLoop\tHVACTemplate:Plant:Tower\tHVACTemplate:Plant:Tower:ObjectReference\tHVACTemplate:System:ConstantVolume\tHVACTemplate:System:DedicatedOutdoorAir\tHVACTemplate:System:DualDuct\tHVACTemplate:System:PackagedVAV\tHVACTemplate:System:Unitary\tHVACTemplate:System:UnitaryHeatPump:AirToAir\tHVACTemplate:System:UnitarySystem\tHVACTemplate:System:VAV\tHVACTemplate:System:VRF\tHVACTemplate:Thermostat\tHVACTemplate:Zone:BaseboardHeat\tHVACTemplate:Zone:ConstantVolume\tHVACTemplate:Zone:DualDuct\tHVACTemplate:Zone:FanCoil\tHVACTemplate:Zone:IdealLoadsAirSystem\tHVACTemplate:Zone:PTAC\tHVACTemplate:Zone:PTHP\tHVACTemplate:Zone:Unitary\tHVACTemplate:Zone:VAV\tHVACTemplate:Zone:VAV:FanPowered\tHVACTemplate:Zone:VAV:HeatAndCool\tHVACTemplate:Zone:VRF\tHVACTemplate:Zone:WaterToAirHeatPump',
  ],
  [
    'io-reference/overview/group-pumps/#',
    'HeaderedPumps:ConstantSpeed\tHeaderedPumps:VariableSpeed\tPump:ConstantSpeed\tPump:VariableSpeed\tPump:VariableSpeed:Condensate',
  ],
  [
    'io-reference/overview/group-heat-recovery/#',
    'HeatExchanger:AirToAir:FlatPlate\tHeatExchanger:AirToAir:SensibleAndLatent\tHeatExchanger:Desiccant:BalancedFlow\tHeatExchanger:Desiccant:BalancedFlow:PerformanceDataType1',
  ],
  ['io-reference/overview/group-hybrid-model/#', 'HybridModel:Zone'],
  [
    'io-reference/energyplus-economics/lifecyclecost-nonrecurringcost/#',
    'LifeCycleCost:NonrecurringCost',
  ],
  ['io-reference/energyplus-economics/lifecyclecost-parameters/#', 'LifeCycleCost:Parameters'],
  [
    'io-reference/energyplus-economics/lifecyclecost-recurringcosts/#',
    'LifeCycleCost:RecurringCosts',
  ],
  [
    'io-reference/energyplus-economics/lifecyclecost-useadjustment/#',
    'LifeCycleCost:UseAdjustment',
  ],
  [
    'io-reference/energyplus-economics/lifecyclecost-usepriceescalation/#',
    'LifeCycleCost:UsePriceEscalation',
  ],
  ['io-reference/overview/group-non-zone-equipment/#', 'LoadProfile:Plant'],
  ['io-reference/standard-output-reports/output-table-annual/#', 'Output:Table:Annual'],
  ['io-reference/standard-output-reports/output-table-monthly/#', 'Output:Table:Monthly'],
  ['io-reference/standard-output-reports/output-table-reportperiod/#', 'Output:Table:ReportPeriod'],
  [
    'io-reference/standard-output-reports/output-table-summaryreports/#',
    'Output:Table:SummaryReports',
  ],
  ['io-reference/standard-output-reports/output-table-timebins/#', 'Output:Table:TimeBins'],
  ['io-reference/standard-output-reports/outputcontrol-table-style/#', 'OutputControl:Table:Style'],
  [
    'io-reference/parametric-objects/#',
    'Parametric:FileNameSuffix\tParametric:Logic\tParametric:RunControl\tParametric:SetValueForRun',
  ],
  [
    'io-reference/overview/group-python-plugins/#',
    'PythonPlugin:Instance\tPythonPlugin:SearchPaths\tPythonPlugin:TrendVariable\tPythonPlugin:Variables',
  ],
  [
    'io-reference/overview/group-refrigeration/#',
    'Refrigeration:AirChiller\tRefrigeration:Case\tRefrigeration:CaseAndWalkInList\tRefrigeration:Compressor\tRefrigeration:CompressorList\tRefrigeration:CompressorRack\tRefrigeration:Condenser:AirCooled\tRefrigeration:Condenser:Cascade\tRefrigeration:Condenser:EvaporativeCooled\tRefrigeration:Condenser:WaterCooled\tRefrigeration:GasCooler:AirCooled\tRefrigeration:SecondarySystem\tRefrigeration:Subcooler\tRefrigeration:System\tRefrigeration:TranscriticalSystem\tRefrigeration:TransferLoadList\tRefrigeration:WalkIn',
  ],
  [
    'io-reference/overview/group-location-climate-weather-file-access/#',
    'RoofIrrigation\tRunPeriod\tRunPeriodControl:DaylightSavingTime\tRunPeriodControl:SpecialDays\tSite:GroundDomain:Basement\tSite:GroundDomain:Slab\tSite:GroundReflectance\tSite:GroundReflectance:SnowModifier\tSite:GroundTemperature:BuildingSurface\tSite:GroundTemperature:Deep\tSite:GroundTemperature:FCfactorMethod\tSite:GroundTemperature:Shallow\tSite:GroundTemperature:Undisturbed:FiniteDifference\tSite:GroundTemperature:Undisturbed:KusudaAchenbach\tSite:GroundTemperature:Undisturbed:Xing\tSite:HeightVariation\tSite:Location\tSite:Precipitation\tSite:SolarAndVisibleSpectrum\tSite:SpectrumData\tSite:VariableLocation\tSite:WaterMainsTemperature\tSite:WeatherStation\tSizingPeriod:DesignDay\tSizingPeriod:WeatherFileConditionType\tSizingPeriod:WeatherFileDays\tWeatherProperty:SkyTemperature',
  ],
  [
    'io-reference/overview/group-room-air-models/#',
    'RoomAir:Node\tRoomAir:Node:AirflowNetwork\tRoomAir:Node:AirflowNetwork:AdjacentSurfaceList\tRoomAir:Node:AirflowNetwork:HVACEquipment\tRoomAir:Node:AirflowNetwork:InternalGains\tRoomAir:TemperaturePattern:ConstantGradient\tRoomAir:TemperaturePattern:NondimensionalHeight\tRoomAir:TemperaturePattern:SurfaceMapping\tRoomAir:TemperaturePattern:TwoGradient\tRoomAir:TemperaturePattern:UserDefined\tRoomAirModelType\tRoomAirSettings:AirflowNetwork\tRoomAirSettings:CrossVentilation\tRoomAirSettings:OneNodeDisplacementVentilation\tRoomAirSettings:ThreeNodeDisplacementVentilation\tRoomAirSettings:UnderFloorAirDistributionExterior\tRoomAirSettings:UnderFloorAirDistributionInterior',
  ],
  [
    'io-reference/overview/group-schedules/#',
    'Schedule:Compact\tSchedule:Constant\tSchedule:Day:Hourly\tSchedule:Day:Interval\tSchedule:Day:List\tSchedule:File\tSchedule:File:Shading\tSchedule:Week:Compact\tSchedule:Week:Daily\tSchedule:Year\tScheduleTypeLimits',
  ],
  [
    'io-reference/overview/group-setpoint-managers/#',
    'SetpointManager:Coldest\tSetpointManager:CondenserEnteringReset\tSetpointManager:CondenserEnteringReset:Ideal\tSetpointManager:FollowGroundTemperature\tSetpointManager:FollowOutdoorAirTemperature\tSetpointManager:FollowSystemNodeTemperature\tSetpointManager:MixedAir\tSetpointManager:MultiZone:Cooling:Average\tSetpointManager:MultiZone:Heating:Average\tSetpointManager:MultiZone:Humidity:Maximum\tSetpointManager:MultiZone:Humidity:Minimum\tSetpointManager:MultiZone:MaximumHumidity:Average\tSetpointManager:MultiZone:MinimumHumidity:Average\tSetpointManager:OutdoorAirPretreat\tSetpointManager:OutdoorAirReset\tSetpointManager:ReturnAirBypassFlow\tSetpointManager:ReturnTemperature:ChilledWater\tSetpointManager:ReturnTemperature:HotWater\tSetpointManager:Scheduled\tSetpointManager:Scheduled:DualSetpoint\tSetpointManager:SingleZone:Cooling\tSetpointManager:SingleZone:Heating\tSetpointManager:SingleZone:Humidity:Maximum\tSetpointManager:SingleZone:Humidity:Minimum\tSetpointManager:SingleZone:OneStageCooling\tSetpointManager:SingleZone:OneStageHeating\tSetpointManager:SingleZone:Reheat\tSetpointManager:SystemNodeReset:Humidity\tSetpointManager:SystemNodeReset:Temperature\tSetpointManager:Warmest\tSetpointManager:WarmestTemperatureFlow',
  ],
  [
    'io-reference/overview/group-solar-collectors/#',
    'SolarCollector:FlatPlate:PhotovoltaicThermal\tSolarCollector:FlatPlate:Water\tSolarCollector:IntegralCollectorStorage\tSolarCollector:UnglazedTranspired\tSolarCollector:UnglazedTranspired:Multisystem\tSolarCollectorPerformance:FlatPlate\tSolarCollectorPerformance:IntegralCollectorStorage\tSolarCollectorPerformance:PhotovoltaicThermal:BIPVT\tSolarCollectorPerformance:PhotovoltaicThermal:Simple',
  ],
  [
    'io-reference/overview/group-zone-equipment/#',
    'SpaceHVAC:EquipmentConnections\tSpaceHVAC:ZoneEquipmentMixer\tSpaceHVAC:ZoneEquipmentSplitter\tSpaceHVAC:ZoneReturnMixer\tZoneHVAC:AirDistributionUnit\tZoneHVAC:EquipmentConnections\tZoneHVAC:EquipmentList',
  ],
  [
    'io-reference/overview/group-performance-tables/#',
    'Table:IndependentVariable\tTable:IndependentVariableList\tTable:Lookup',
  ],
  ['io-reference/overview/group-plant-condenser-flow-control/#', 'TemperingValve'],
  [
    'io-reference/overview/group-water-heaters/#',
    'ThermalStorage:ChilledWater:Mixed\tThermalStorage:ChilledWater:Stratified\tThermalStorage:HotWater:Stratified\tThermalStorage:Ice:Detailed\tThermalStorage:Ice:Simple\tThermalStorage:PCM\tThermalStorage:Sizing\tWaterHeater:HeatPump:PumpedCondenser\tWaterHeater:HeatPump:WrappedCondenser\tWaterHeater:Mixed\tWaterHeater:Sizing\tWaterHeater:Stratified',
  ],
  [
    'io-reference/overview/group-zone-controls-thermostats/#',
    'ThermostatSetpoint:DualSetpoint\tThermostatSetpoint:SingleCooling\tThermostatSetpoint:SingleHeating\tThermostatSetpoint:SingleHeatingOrCooling\tThermostatSetpoint:ThermalComfort:Fanger:DualSetpoint\tThermostatSetpoint:ThermalComfort:Fanger:SingleCooling\tThermostatSetpoint:ThermalComfort:Fanger:SingleHeating\tThermostatSetpoint:ThermalComfort:Fanger:SingleHeatingOrCooling\tZoneControl:ContaminantController\tZoneControl:Humidistat\tZoneControl:Thermostat\tZoneControl:Thermostat:OperativeTemperature\tZoneControl:Thermostat:StagedDualSetpoint\tZoneControl:Thermostat:TemperatureAndHumidity\tZoneControl:Thermostat:ThermalComfort',
  ],
  ['io-reference/energyplus-economics/utilitycost-charge-block/#', 'UtilityCost:Charge:Block'],
  ['io-reference/energyplus-economics/utilitycost-charge-simple/#', 'UtilityCost:Charge:Simple'],
  ['io-reference/energyplus-economics/utilitycost-computation/#', 'UtilityCost:Computation'],
  ['io-reference/energyplus-economics/utilitycost-qualify/#', 'UtilityCost:Qualify'],
  ['io-reference/energyplus-economics/utilitycost-ratchet/#', 'UtilityCost:Ratchet'],
  ['io-reference/energyplus-economics/utilitycost-tariff/#', 'UtilityCost:Tariff'],
  ['io-reference/energyplus-economics/utilitycost-variable/#', 'UtilityCost:Variable'],
  [
    'io-reference/overview/group-water-systems/#',
    'WaterUse:Connections\tWaterUse:Equipment\tWaterUse:RainCollector\tWaterUse:Storage\tWaterUse:Well',
  ],
  [
    'io-reference/overview/group-airflow/#',
    'ZoneAirBalance:OutdoorAir\tZoneAirMassFlowConservation\tZoneCoolTower:Shower\tZoneCrossMixing\tZoneEarthtube\tZoneEarthtube:Parameters\tZoneInfiltration:DesignFlowRate\tZoneInfiltration:EffectiveLeakageArea\tZoneInfiltration:FlowCoefficient\tZoneMixing\tZoneRefrigerationDoorMixing\tZoneThermalChimney\tZoneVentilation:DesignFlowRate\tZoneVentilation:WindandStackOpenArea',
  ],
  [
    'io-reference/overview/group-radiative-convective-units/#',
    'ZoneHVAC:Baseboard:Convective:Electric\tZoneHVAC:Baseboard:Convective:Water\tZoneHVAC:Baseboard:RadiantConvective:Electric\tZoneHVAC:Baseboard:RadiantConvective:Steam\tZoneHVAC:Baseboard:RadiantConvective:Steam:Design\tZoneHVAC:Baseboard:RadiantConvective:Water\tZoneHVAC:Baseboard:RadiantConvective:Water:Design\tZoneHVAC:CoolingPanel:RadiantConvective:Water\tZoneHVAC:HighTemperatureRadiant\tZoneHVAC:LowTemperatureRadiant:ConstantFlow\tZoneHVAC:LowTemperatureRadiant:ConstantFlow:Design\tZoneHVAC:LowTemperatureRadiant:Electric\tZoneHVAC:LowTemperatureRadiant:SurfaceGroup\tZoneHVAC:LowTemperatureRadiant:VariableFlow\tZoneHVAC:LowTemperatureRadiant:VariableFlow:Design\tZoneHVAC:VentilatedSlab\tZoneHVAC:VentilatedSlab:SlabGroup',
  ],
  [
    'io-reference/overview/group-zone-forced-air-units/#',
    'ZoneHVAC:Dehumidifier:DX\tZoneHVAC:EnergyRecoveryVentilator\tZoneHVAC:EvaporativeCoolerUnit\tZoneHVAC:FourPipeFanCoil\tZoneHVAC:HybridUnitaryHVAC\tZoneHVAC:IdealLoadsAirSystem\tZoneHVAC:OutdoorAirUnit\tZoneHVAC:OutdoorAirUnit:EquipmentList\tZoneHVAC:PackagedTerminalAirConditioner\tZoneHVAC:PackagedTerminalHeatPump\tZoneHVAC:RefrigerationChillerSet\tZoneHVAC:TerminalUnit:VariableRefrigerantFlow\tZoneHVAC:UnitHeater\tZoneHVAC:UnitVentilator\tZoneHVAC:WaterToAirHeatPump\tZoneHVAC:WindowAirConditioner',
  ],
];
