import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { beforeAll, describe, expect, it } from 'vitest';

import type { Schema } from '@idfkit/schemas';
import { localBundle } from '@idfkit/schemas/node';

import {
  docsUrlForObject,
  engineeringReferenceUrl,
  ioReferenceUrl,
  searchUrl,
  type DocsUrl,
} from '../src/docs-url/index.js';

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));

/** Versions with documentation, as this module gates on them. */
const VERSIONS = [
  '8.9.0',
  '9.0.1',
  '9.1.0',
  '9.2.0',
  '9.3.0',
  '9.4.0',
  '9.5.0',
  '9.6.0',
  '22.1.0',
  '22.2.0',
  '23.1.0',
  '23.2.0',
  '24.1.0',
  '24.2.0',
  '25.1.0',
  '25.2.0',
  '26.1.0',
];

describe('documentation URLs', () => {
  it('addresses an object page', () => {
    expect(ioReferenceUrl('Zone', '26.1.0')).toEqual({
      url: 'https://docs.idfkit.com/v26.1/io-reference/overview/group-thermal-zone-description-geometry/#zone',
      docSet: 'io-reference',
      version: 'v26.1',
      label: 'Zone — I/O Reference',
    } satisfies DocsUrl);
  });

  it('addresses the engineering reference and the search page', () => {
    expect(engineeringReferenceUrl('25.2.0')?.url).toBe(
      'https://docs.idfkit.com/v25.2/engineering-reference/'
    );
    expect(searchUrl('chiller', '25.2.0')).toEqual({
      url: 'https://docs.idfkit.com/v25.2/io-reference/overview/',
      docSet: 'search',
      version: 'v25.2',
      label: 'Search: chiller',
    } satisfies DocsUrl);
  });

  it('honours a base URL override', () => {
    expect(
      ioReferenceUrl('Zone', '26.1.0', undefined, { baseUrl: 'http://localhost:8000' })?.url
    ).toBe(
      'http://localhost:8000/v26.1/io-reference/overview/group-thermal-zone-description-geometry/#zone'
    );
  });

  it('returns undefined rather than a dead link for a version without docs', () => {
    // 9.0.1 is supported and 9.0.0 is not; a nearest-match rule would wrongly
    // accept the latter and address a page that does not exist.
    expect(ioReferenceUrl('Zone', '9.0.0')).toBeUndefined();
    expect(ioReferenceUrl('Zone', '26.1.1')).toBeUndefined();
    expect(ioReferenceUrl('Zone', 'not-a-version')).toBeUndefined();
    expect(engineeringReferenceUrl('9.0.0')).toBeUndefined();
    expect(searchUrl('chiller', '9.0.0')).toBeUndefined();
  });

  it('returns undefined for an object type outside the mapping and no schema', () => {
    // The documented divergence: Python would load the latest schema here and
    // try the group fallback. Loading is I/O, which this entry point forbids.
    expect(ioReferenceUrl('GroundHeatTransfer:Slab:XFACE', '26.1.0')).toBeUndefined();
    expect(docsUrlForObject('NotAnObjectType', '26.1.0')).toBeUndefined();
  });

  it('covers every documented version', () => {
    for (const version of VERSIONS) {
      expect(ioReferenceUrl('Zone', version), version).toBeDefined();
    }
  });
});

describe('documented versions', () => {
  it('matches the versions the schema bundle ships', async () => {
    // Both lists descend from the same EnergyPlus release set. A version in one
    // and not the other is how the two libraries start disagreeing about
    // whether a link exists at all.
    const versions = await localBundle().versions();
    expect([...versions].sort()).toEqual([...VERSIONS].sort());
  });
});

// ---------------------------------------------------------------------------
// Byte-identity against Python
// ---------------------------------------------------------------------------

const IDFKIT_REPO = here('../../../../idfkit');
const GROUND_TRUTH = here('../src/docs-url/python-ground-truth.py');

/** Every URL Python builds, keyed `<call>|<version>|<argument>`. */
type Truth = Record<string, [string, string, string, string] | null>;

function pythonGroundTruth(): Truth | undefined {
  if (!existsSync(`${IDFKIT_REPO}/src/idfkit/docs.py`)) return undefined;
  try {
    const stdout = execFileSync('uv', ['run', 'python', GROUND_TRUTH], {
      cwd: IDFKIT_REPO,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    return JSON.parse(stdout) as Truth;
  } catch {
    return undefined;
  }
}

/**
 * The port's reason to exist: the same object, at the same version, has to
 * address the same page in both libraries.
 *
 * Ground truth is generated by running Python, not by restating its rules here,
 * because a reimplementation of the rules would agree with the port by
 * construction and prove nothing. The suite skips when a sibling idfkit
 * checkout or `uv` is missing, so CI without them still passes and a developer
 * machine gets the real check.
 */
describe('byte-identity with Python', () => {
  let truth: Truth | undefined;
  const schemas = new Map<string, Schema>();

  beforeAll(async () => {
    truth = pythonGroundTruth();
    if (truth === undefined) return;
    const bundle = localBundle();
    for (const version of VERSIONS) schemas.set(version, await bundle.load(version));
  }, 120_000);

  it('produces the URL Python produces, for every case Python was asked', () => {
    if (truth === undefined) {
      console.warn('Skipping: no sibling idfkit checkout or no uv on PATH.');
      return;
    }

    const mismatches: string[] = [];
    let compared = 0;

    for (const [key, expected] of Object.entries(truth)) {
      const [call, version, argument] = key.split('|') as [string, string, string];
      let result: DocsUrl | undefined;
      switch (call) {
        case 'io':
          result = ioReferenceUrl(argument, version);
          break;
        case 'fallback':
          result = ioReferenceUrl(argument, version, schemas.get(version));
          break;
        case 'obj':
          result = docsUrlForObject(argument, version);
          break;
        case 'eng':
          result = engineeringReferenceUrl(version);
          break;
        case 'search':
          result = searchUrl(argument, version);
          break;
        default:
          throw new Error(`Unknown call in ground truth: ${key}`);
      }

      compared++;
      const actual =
        result === undefined ? null : [result.url, result.docSet, result.version, result.label];
      if (JSON.stringify(actual) !== JSON.stringify(expected)) {
        mismatches.push(
          `${key}\n  python: ${JSON.stringify(expected)}\n  ts:     ${JSON.stringify(actual)}`
        );
      }
    }

    expect(compared).toBeGreaterThan(10_000);
    expect(mismatches).toEqual([]);
  }, 120_000);
});
