#!/usr/bin/env node
/**
 * Generate TypeScript interfaces for every object type in a schema version.
 *
 * This is the piece that has no Python counterpart and is the main reason a
 * JavaScript port is worth doing rather than merely possible. The Python
 * library resolves `zone.ceiling_height` at runtime through `__getattr__`; an
 * editor cannot see through that, so nothing completes and nothing is checked.
 * Here the same information is emitted as static types, so a typo in a field
 * name is a compile error and every field, unit, and choice list is one
 * keystroke away in the editor.
 *
 * Usage: node scripts/emit-types.mjs [version...] [--out <dir>] [--no-notes]
 */

import { gunzipSync } from 'node:zlib';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, '..');
const SCHEMA_SRC = resolve(PKG, '../../../idfkit/src/idfkit/schemas');

const argv = process.argv.slice(2);
const outFlag = argv.indexOf('--out');
const OUT = outFlag !== -1 ? resolve(argv[outFlag + 1]) : join(PKG, 'src', 'types');
const WITH_NOTES = !argv.includes('--no-notes');
const versions = argv.filter((a) => /^\d+\.\d+\.\d+$/.test(a));
if (versions.length === 0) versions.push('26.1.0');

/** `26.1.0` -> `V26-1-0`. */
function versionDir(version) {
  return `V${version.split('.').join('-')}`;
}

/** `26.1.0` -> `v26-1`, the module name callers import. */
function moduleName(version) {
  const [major, minor] = version.split('.');
  return `v${major}-${minor}`;
}

/**
 * Turn an EnergyPlus type name into a TypeScript identifier.
 * `Coil:Cooling:DX:SingleSpeed` -> `Coil_Cooling_DX_SingleSpeed`
 */
function identifier(typeName) {
  let id = typeName.replace(/[^A-Za-z0-9_$]/g, '_');
  if (/^[0-9]/.test(id)) id = `_${id}`;
  return id;
}

const RESERVED = new Set(['default', 'function', 'new', 'delete', 'class', 'enum', 'interface']);

/** Quote a field name if it is not a bare JS identifier. */
function propertyKey(field) {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(field) && !RESERVED.has(field)) return field;
  return JSON.stringify(field);
}

function escapeComment(text) {
  return String(text).replace(/\*\//g, '*\\/').trim();
}

/** Render one field's TypeScript type. */
function fieldType(def) {
  let effective = def;
  let auto = false;
  if (Array.isArray(def.anyOf)) {
    const numeric = def.anyOf.find((b) => b.type === 'number');
    if (numeric) {
      effective = { ...numeric, enum: def.enum };
      auto = true;
    } else {
      effective = def.anyOf[0] ?? {};
    }
  }

  if (effective.type === 'array') return null; // handled by the extensible key

  const choices = (effective.enum ?? []).filter((v) => v !== '');
  if (effective.type === 'number' || effective.type === 'integer') {
    // `Autosize` and `Autocalculate` are legal in numeric fields, so the type
    // has to admit them or ordinary models will not typecheck.
    return auto ? "number | 'Autosize' | 'Autocalculate'" : 'number';
  }
  if (choices.length > 0 && choices.length <= 60) {
    // Union of literals, so choice fields autocomplete. Very large choice lists
    // (schedule type limits, refrigerant names) fall back to `string`: they are
    // open-ended in practice and the union hurts editor performance.
    return choices.map((c) => JSON.stringify(c)).join(' | ');
  }
  return 'string';
}

function docComment(indent, lines) {
  const kept = lines.filter((line) => line !== undefined && line !== '');
  if (kept.length === 0) return '';
  if (kept.length === 1) return `${indent}/** ${escapeComment(kept[0])} */\n`;
  return `${indent}/**\n${kept.map((l) => `${indent} * ${escapeComment(l)}`).join('\n')}\n${indent} */\n`;
}

function emitVersion(version) {
  const path = join(SCHEMA_SRC, versionDir(version), 'Energy+.schema.epJSON.gz');
  const schema = JSON.parse(gunzipSync(readFileSync(path)).toString('utf8'));
  const types = schema.properties ?? {};

  const out = [];
  out.push(`// Generated by scripts/emit-types.mjs for EnergyPlus ${version}. Do not edit.`);
  out.push(`// Regenerate with: npm run codegen -w @idfkit/core -- ${version}`);
  out.push('');
  out.push("import type { ExtensibleGroup } from '../object.js';");
  out.push('');
  out.push(`/** EnergyPlus version these interfaces describe. */`);
  out.push(`export const VERSION = ${JSON.stringify(version)};`);
  out.push('');

  const exported = new Map();

  for (const [typeName, raw] of Object.entries(types)) {
    const id = identifier(typeName);
    if (exported.has(id)) continue;
    exported.set(id, typeName);

    const legacy = raw.legacy_idd ?? {};
    const fieldInfo = legacy.field_info ?? {};
    const body = Object.values(raw.patternProperties ?? {})[0] ?? {};
    const props = body.properties ?? {};
    const required = new Set(body.required ?? []);
    const order = (legacy.fields ?? []).filter((f) => f !== 'name');

    out.push(
      docComment('', [
        typeName,
        WITH_NOTES ? raw.memo : undefined,
        raw.group ? `Group: ${raw.group}` : undefined,
      ]).trimEnd()
    );
    out.push(`export interface ${id} {`);

    for (const field of order) {
      const def = props[field];
      if (def === undefined) continue;
      const rendered = fieldType(def);
      if (rendered === null) continue;

      const info = fieldInfo[field] ?? {};
      const comment = docComment('  ', [
        info.field_name,
        WITH_NOTES ? def.note : undefined,
        def.units ? `Units: ${def.units}` : undefined,
        def.default !== undefined ? `Default: ${JSON.stringify(def.default)}` : undefined,
      ]);
      const optional = required.has(field) ? '' : '?';
      out.push(`${comment}  ${propertyKey(field)}${optional}: ${rendered};`);
    }

    if (legacy.extension && legacy.extensibles?.length) {
      const comment = docComment('  ', [`Repeating group: ${legacy.extensibles.join(', ')}`]);
      out.push(`${comment}  ${propertyKey(legacy.extension)}?: ExtensibleGroup[];`);
    }

    out.push('}');
    out.push('');
  }

  // The map is the only thing a caller needs to import. It is a type, so it
  // costs nothing at runtime and disappears entirely from the emitted JS.
  out.push('/**');
  out.push(` * Object type name to field interface, for EnergyPlus ${version}.`);
  out.push(' *');
  out.push(' * Parameterize a document with this to get static field checking:');
  out.push(' * ```ts');
  out.push(" * import type { TypeMap } from '@idfkit/core/types/v26-1';");
  out.push(' * const doc = await loadIdf<TypeMap>(path);');
  out.push(" * doc.all('Zone').first?.ceiling_height;  // number | undefined");
  out.push(' * ```');
  out.push(' */');
  out.push('export type TypeMap = {');
  for (const [id, typeName] of exported) {
    out.push(`  ${propertyKey(typeName)}: ${id};`);
  }
  out.push('};');
  out.push('');

  mkdirSync(OUT, { recursive: true });
  const file = join(OUT, `${moduleName(version)}.ts`);
  const text = `${out.join('\n')}\n`;
  writeFileSync(file, text);
  return { file, bytes: text.length, count: exported.size };
}

for (const version of versions) {
  const { file, bytes, count } = emitVersion(version);
  console.log(`${version}  ${count} types  ${(bytes / 1024).toFixed(0)} KB  -> ${file}`);
}
